spring.application.name=study_platform
spring.mongodb.uri=mongodb+srv://admin:123123123@cluster0.9tdoyrw.mongodb.net/study_platform
app.jwt.secret=MySecretKey12345678912345678912345678
# 24 heures en millisecondes
app.jwt.expiration=86400000