spring.application.name=study_platform
spring.mongodb.uri=mongodb+srv://admin:123123123@cluster0.9tdoyrw.mongodb.net/study_platform
app.jwt.secret=MySecretKey12345678912345678912345678
# 7 jours en millisecondes
app.jwt.expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karimakarema604@gmail.com
spring.mail.password=ajvexhsocjbztiss
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG